version: "3"

services: 
  zookeeper:
    image: bitnami/zookeeper:3
    hostname: zookeeper-server
    environment: 
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks: 
      - net

  kafka:
    image: bitnami/kafka:2.5.0
    hostname: kafka-server
    ports: 
      - "9092:9092"
      - "9093:9093"
    environment: 
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://:9092,EXTERNAL://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka:9092,EXTERNAL://localhost:9093
    networks: 
      - net
    depends_on:
      - zookeeper

  kafka_manager:
    image: hlebalbau/kafka-manager:3.0.0.5
    hostname: kafkamanager-server
    ports: 
      - "9000:9000"
    environment: 
      ZK_HOSTS: zookeeper:2181
      #APPLICATION_SECRET: "secret-key"
      #- KAFKA_MANAGER_AUTH_ENABLED=true
      #- KAFKA_MANAGER_USERNAME=admin
      #- KAFKA_MANAGER_PASSWORD=admin
    command: -Dpidfile.path=/dev/null
    networks:
      - net
    depends_on:
      - kafka

networks: 
  net:
    driver: bridge
